
include mak.inc

LIBS	= 

CXXINC	=
INC	=
DEFS	= 
#CFLAGS	= -g 
CFLAGS	= -O3 -fastsse -openmp
FFLAGS	= -g -r8 
LDFLAGS	= -openmp

CXX	= pgCC
CC	= pgcc
FC	= pgf90

RM	= rm -f

.C.o: ; $(CXX) -c $(CFLAGS) $*.C
.c.o: ; $(CC) -c $(CFLAGS) $*.c
.f.o: ; $(FC) -c $(FFLAGS) $*.f

all: $(EXEC)

$(EXEC): $(OBJS) 
	$(CXX) $(LDFLAGS) -o $@ $(INC) $(OBJS) $(LIBS) 

.PHONY : clean
clean:
	-$(RM) *.o *~ $(EXEC)

depend:
	makedepend $(INCLUDES) *.C

