
include mak.inc

LIBS	= 

CXXINC	=
INC	=
DEFS	= 
#CFLAGS	= -O2 
CFLAGS	= -O3 -parallel -par-report2 -openmp
FFLAGS	= -O2 -r8 
LDFLAGS	= -parallel -openmp

CXX	= icpc
CC	= icc
FC	= ifort

RM	= rm -f

.C.o: ; $(CXX) -c $(CFLAGS) $*.C
.c.o: ; $(CC) -c $(CFLAGS) $*.c
.f.o: ; $(FC) -c $(FFLAGS) $*.f

all: $(EXEC)

$(EXEC): $(OBJS) 
	$(CXX) $(LDFLAGS) -o $@ $(INC) $(OBJS) $(LIBS)

.PHONY : clean
clean:
	-$(RM) *.o *~ $(EXEC)

depend:
	makedepend $(INCLUDES) *.C

